name: Packer CI Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Run packer fmt
        run: |
          packer init packer
          packer fmt packer

      - name: Run packer validate
        run: |
          cd packer
          packer validate -var "project_id=${{ secrets.PROJECT_ID }}" \
                          -var "zone=${{ secrets.ZONE }}" \
                          -var "db_user=${{ secrets.DB_USER }}" \
                          -var "db_password=${{ secrets.DB_PASSWORD }}" \
                          -var "db_name=${{ secrets.DB_NAME }}" \
                          image.pkr.hcl
