name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        curl -L -o packer.zip https://releases.hashicorp.com/packer/1.8.7/packer_1.8.7_linux_amd64.zip
        unzip -o packer.zip
        sudo mv packer /usr/local/bin/
        packer --version

    - name: Run Packer Fmt
      run: |
        packer fmt -check -diff packer/image.pkr.hcl

    - name: Run Packer Validate
      run: |
        packer validate packer/image.pkr.hcl
