name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: 1.8.6

    - name: Initialize Packer Plugins
      run: |
        packer init packer/image.pkr.hcl

    - name: Run Packer Fmt
      run: |
        packer fmt -check -diff packer/image.pkr.hcl

    - name: Build Application Artifact
      run: |
        zip -r app.zip code_files requirements.txt

    - name: Check Environment Variables
      run: |
        echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
        echo "ZONE=${{ secrets.GCP_ZONE }}"
        echo "DB_USER=${{ secrets.DB_USER }}"
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        echo "DB_NAME=${{ secrets.DB_NAME }}"

    - name: Run Packer Validate
      working-directory: ./packer
      run: |
        packer validate \
          -var "project_id=dev-gcp-8989" \
          -var "zone=us-west4-b" \
          -var "db_user=${{ secrets.DB_USER }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}" \
          -var "db_name=${{ secrets.DB_NAME }}" \
          image.pkr.hcl

