name: Packer Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: 1.8.6

    - name: Initialize Packer Plugins
      run: |
        packer init packer/image.pkr.hcl

    - name: Run Packer Fmt
      run: |
        packer fmt -check -diff packer/image.pkr.hcl

    - name: Build Application Artifact
      run: |
        zip -r app.zip code_files requirements.txt

    - name: Run Packer Validate
      run: |
        cd packer
        packer validate \
          -var "project_id=${{ secrets.PROJECT_ID }}" \
          -var "zone=${{ secrets.ZONE }}" \
          -var "db_user=${{ secrets.DB_USER }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}" \
          -var "db_name=${{ secrets.DB_NAME }}" \
          image.pkr.hcl

