name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: 1.8.6

    - name: Initialize Packer Plugins
      run: |
        packer init packer/image.pkr.hcl

    - name: Run Packer Fmt
      run: |
        packer fmt -check -diff packer/image.pkr.hcl

    - name: Run Packer Validate
      run: |
        packer validate \
          -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var "zone=${{ secrets.GCP_ZONE }}" \
          -var "db_user=${{ secrets.DB_USER }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}" \
          -var "db_name=${{ secrets.DB_NAME }}" \
          packer/image.pkr.hcl

