name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Environment Variables
      run: |
        echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
        echo "ZONE=${{ secrets.GCP_ZONE }}"
        echo "DB_USER=${{ secrets.DB_USER }}"
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        echo "DB_NAME=${{ secrets.DB_NAME }}"